// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1Fvd-wD0RSM9kjjijY_rWNtxFNjJCdHw',
    appId: '1:1040777059093:web:62287e1ce36d5f6e51671c',
    messagingSenderId: '1040777059093',
    projectId: 'patina-engine',
    authDomain: 'patina-engine.firebaseapp.com',
    storageBucket: 'patina-engine.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRHW9rAvuUDawhKMEF3MmPzFgOGeVgsZE',
    appId: '1:1040777059093:android:19491e1de93d0a5b51671c',
    messagingSenderId: '1040777059093',
    projectId: 'patina-engine',
    storageBucket: 'patina-engine.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNZNV2_CET_Cezn97wMfCuO6WtUpYrh1w',
    appId: '1:1040777059093:ios:fc40a7d3641f104d51671c',
    messagingSenderId: '1040777059093',
    projectId: 'patina-engine',
    storageBucket: 'patina-engine.firebasestorage.app',
    iosBundleId: 'com.example.patinaEngine',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNZNV2_CET_Cezn97wMfCuO6WtUpYrh1w',
    appId: '1:1040777059093:ios:fc40a7d3641f104d51671c',
    messagingSenderId: '1040777059093',
    projectId: 'patina-engine',
    storageBucket: 'patina-engine.firebasestorage.app',
    iosBundleId: 'com.example.patinaEngine',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA1Fvd-wD0RSM9kjjijY_rWNtxFNjJCdHw',
    appId: '1:1040777059093:web:662cdafb8cda910551671c',
    messagingSenderId: '1040777059093',
    projectId: 'patina-engine',
    authDomain: 'patina-engine.firebaseapp.com',
    storageBucket: 'patina-engine.firebasestorage.app',
  );

}